# @package _group_
run:
  dir: ${location.out_root_dir}/contour_removal_${now:%Y-%m-%d_%H-%M-%S}_${hydra:job.name}_${hydra:job.config_name}_${run_title}
sweep:
  dir: ${hydra:run.dir}_sweep
  subdir: ${hydra.job.num}
